# Generated by Django 5.2.6 on 2025-10-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titlte',
            new_name='title',
        ),
    ]
